--- 
/var/log: 
- syslog
- ftp.log
- mail.log
/Library/Logs/DirectoryService: 
- DirectoryService.error.log
- DirectoryService.server.log
/Library/Logs/AppleFileService: 
- AppleFileServiceAccess.log
- AppleFileServiceError.log
